[package]
name = "sumcheck-benches"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.4.0"
ark-poly = "0.4.0"
ark-std ="0.4.0"
ark-bn254 = "0.4.0"
space-efficient-sumcheck = { path = "../." }

[profile.release]
debug = true
